name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: pip install beancount
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: lint, build, test and package
        run: |
          npm install -g vsce
          yarn install
          yarn lint
          yarn test
          vsce package
